languaje: python

env:
  - DOCKER_COMPOSE_VERSION=1.21.1

before_install:
  # Install docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce 
  # Update docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# Probe it can be installed
script: docker-compose run --rm --service-ports web odoo -d staging -i test_module --stop-after-init --xmlrpc-port=8070

# Run unit tests :D
after_script: script: docker-compose run --rm --service-ports web odoo -d staging -i test_module --test-enable --stop-after-init --xmlrpc-port=8070