version: '2'
services:
    web:
        container_name: odoo_cookbook_dev_web
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
          - db
        ports:
          - "8072:8069"
        volumes:
          - "odoo-web-data-cookbook:/var/lib/odoo"
          - "./extra-addons:/mnt/extra-addons/"

    db:
        container_name: odoo_cookbook_dev_db
        image: postgres:9.4
        environment:
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_USER=odoo
          - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
          - odoo-db-data-cookbook:/var/lib/postgresql/data/pgdata

volumes:
    odoo-web-data-cookbook:
    odoo-db-data-cookbook:
